### ISSUE TITLE
Type-checking failure in node_modules on a fresh Ember app

### ISSUE THREAD

**Issue by collinsmwade** [typed-ember/ember-cli-typescript#1515]
**My environment:**
- npm: 8.13.2
- node: 14.19.3
- ember-cli: 4.4.0
- os: darwin x64

### Which package(s) does this problem pertain to?
  - [x] @types/ember
  - [x] @types/ember__string
  - [ ] @types/ember__polyfills
  - [x] @types/ember__object
  - [ ] @types/ember__utils
  - [x] @types/ember__array
  - [x] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [x] @types/ember__controller
  - [x] @types/ember__component
  - [x] @types/ember__routing
  - [x] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [x] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support

npm start;
```
Invoking `ember serve` instead of `npm start` has the same issue.

### Now about that bug. What did you expect to see?
I expect the ember server to start.

### What happened instead?
I encountered an assortment of type errors from ember node_modules. [The full output is available here](https://gist.github.com/collinsmwade/500460d77932aea49b634167f0ae1f08), but some of these errors are as follows:
```
node_modules/@types/ember__controller/index.d.ts:47:22 - error TS2417: Class static side 'typeof Controller' incorrectly extends base class static side 'Readonly<typeof EmberObject>'.
  The types of 'prototype.addObserver' are incompatible between these types.
    Type '{ <Target>(key: keyof Controller, target: Target, method: ObserverMethod<Target, Controller>): void; (key: keyof Controller, method: ObserverMethod<...>): void; }' is not assignable to type '{ <Target>(key: keyof Object, target: Target, method: ObserverMethod<Target, Object>): void; (key: keyof Object, method: ObserverMethod<Object, Object>): void; }'.
      Types of parameters 'method' and 'method' are incompatible.
        Type 'ObserverMethod<any, Object>' is not assignable to type 'ObserverMethod<any, Controller>'.
          Type '(this: any, sender: Object, key: keyof Object, value: any, rev: number) => void' is not assignable to type 'ObserverMethod<any, Controller>'.
            Type '(this: any, sender: Object, key: keyof Object, value: any, rev: number) => void' is not assignable to type '(this: any, sender: Controller, key: keyof Controller, value: any, rev: number) => void'.
              Types of parameters 'key' and 'key' are incompatible.
                Type 'keyof Controller' is not assignable to type 'keyof Object'.
                  Type '"__ember_mixin__"' is not assignable to type 'keyof Object'.

node_modules/@types/ember__object/proxy.d.ts:37:5 - error TS2416: Property 'setProperties' in type 'ObjectProxy<T>' is not assignable to the same property in base type 'EmberObject'.
  Type '<K extends keyof this | keyof T>(hash: Pick<UnwrapComputedPropertySetters<this & T>, K>) => Pick<UnwrapComputedPropertySetters<this & T>, K>' is not assignable to type '<T, K extends keyof T>(this: ComputedPropertySetters<T>, hash: Pick<T, K>) => Pick<T, K>'.
    Types of parameters 'hash' and 'hash' are incompatible.
      Type 'Pick<T, K>' is not assignable to type 'Pick<UnwrapComputedPropertySetters<this & T>, keyof this | keyof T>'.
        Type 'keyof this | keyof T' is not assignable to type 'K'.
          'keyof this | keyof T' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
            Type 'keyof this' is not assignable to type 'K'.
              'keyof this' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
                Type 'string | number | symbol' is not assignable to type 'K'.
                  'string | number | symbol' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.
                    Type 'string' is not assignable to type 'K'.
                      'string' is assignable to the constraint of type 'K', but 'K' could be instantiated with a different subtype of constraint 'string | number | symbol'.

node_modules/@types/ember__array/mutable.d.ts:12:11 - error TS2320: Interface 'MutableArray<T>' cannot simultaneously extend types 'EmberArray<T>' and 'MutableEnumerable<T>'.
  Named property 'compact' of types 'EmberArray<T>' and 'MutableEnumerable<T>' are not identical.
```

**Comment by collinsmwade** [comment]
In addition to Ember 4 I also encountered this issue creating a new project with `ember-cli@3.28`

**Comment by dfreeman** [comment]
Somehow the old 2.x version of `@types/ember-data` seems to have gotten tagged as `latest` in the npm registry https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60742

Getting that cleared up should solve this problem, but in the meantime if you manually update your dependency on `@types/ember-data` from `^2.14.28` to `^4.0.2` (and clear out the related `@types/ember*` entries from your lockfile so they have a chance to re-resolve), that should get you on the actual latest version of those types.

**Comment by collinsmwade** [comment]
It worked with npm! Thanks so much. :) 
However it doesn't seem to fix things on `yarn`-managed ember apps.

**Comment by yavuzitconsulting** [comment]
If you still have this issue (using npm/yarn), the team from [https://github.com/cryptNG](CryptNG) found a solution.

After following @collinsmwade 's comment  and setting 
`@types/ember-data from ^2.14.28 to ^4.0.2` 
you still have a type resolution issue, since some of the packages referenced within the installed node modules (in node_modules/@types) still reference ember-data:latest, and thus, resolve to the old version of ember data (2.x)

Workaround for this issue, until the fix is deployed here:

In your package.json, add a dependency resolution like so:

{
  "name": "project",
  "version": "1.0.0",
  "dependencies": {
[...]
  },
  **"resolutions": {
    "@types/ember-data": "4.0.2"
  },**
  [...]
}

this will fix the typescript issues, don't forget to remove this after it has been fixed in ember-cli-typescript

**Comment by dfreeman** [comment]
As I said, this is an issue with DefinitelyTyped's publishing process—there's nothing to fix in `ember-cli-typescript` itself 🙂 

As long as the npm registry (which is also where Yarn pulls packages from) believes that v2.14.28 is the latest release of `@types/ember-data`, anyone who installs it without explicitly saying they want v4 is going to get those outdated types. The same is true for transitive `*`-constrained dependencies on `@types/ember-data` you might have via other packages.

Landing https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61176 (or anything else that will trigger a new release) should take care of it, and I'm happy to keep this issue open until that happens, but I do want to be clear that our hands are tied and this isn't something we can fix here.

**Comment by dfreeman** [comment]
This should now be resolved with the release of v4.4.0 of `@types/ember-data`.

```
$ npm info @types/ember-data@latest                                                                                                                                                                         

@types/ember-data@4.4.0 | MIT | deps: 3 | versions: 69
TypeScript definitions for ember-data
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ember-data
```

If anyone is still running into issues here after clearing any references to v2 of the package from their `package.json` and lockfile, leave a comment and we can investigate further, but I think that release should put this issue to bed.
